reminders = [
    "Don't forget your prayers. 🕌✨",
    "Make a good action today. 🌟",
    "Don't forget that heaven is under your mother's feet. Take care of her and tell her good words today. ❤️👩‍👧",
    "Remember to say 'Bismillah' before starting anything. 🕋",
    "Reflect on the blessings you have and be grateful. 🙏",
    "Help someone in need today; your good deeds will be rewarded. 🤝",
    "Recite Quran daily; it's a source of peace and guidance. 📖",
    "Make dua (supplication) for yourself and others. 🌙",
    "Smile and be kind to those around you; it's a charity. 😊",
    "Stay away from negativity and surround yourself with positivity. ☀️",
    "Seek knowledge; it is an obligation upon every Muslim. 📚",
    "Do not forget to give charity (zakat), no matter how small. 💖",
    "Remember to treat your spouse with kindness; marriage is half your faith! 💍",
    "Do something special for your partner today; small acts of love go a long way. ❤️",
    "Stop playing League of Legends and go increase your faith! 🎮➡️📖",
    "You will not get out of Gold just by playing games; go read some Quran, brother! 🥇➡️📖",
    "Take a moment to reflect on your goals and how they align with your faith. 🎯",
    "Practice patience today; it’s a virtue that brings peace. 🕊️",
    "Don't forget to engage in dhikr (remembrance of Allah) throughout your day. 🕋",
    "Give a smile to someone today; it’s a form of charity. 😊",
    "Find time to volunteer; serving others is a way to serve Allah. 🤲",
    "Remember, the best among you are those who have the best manners. 🥰",
    "Set a goal to read one page of Quran each day; small steps lead to big changes! 📖➡️🌟",
]
